=== jmapper-framework/jmapper-core/jmapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- 
	jmapper:
		(class+)
 -->
	<xs:element name="jmapper">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="class" type="jmapperClass" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
<!-- 
	class:
		name = string
		(global?,attribute+,conversion*)
 -->
	<xs:complexType name="jmapperClass">
		<xs:sequence>
			<xs:element name="global" type="jmapperGlobal" minOccurs="0"/>
			<xs:element name="attribute" type="jmapperAttribute" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="conversion" type="jmapperConversion" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string"/>
	</xs:complexType>

<!--
	conversion:
		name = string
		from = string
		to = string
		type = STATIC|DYNAMIC 
 -->
	<xs:complexType name="jmapperConversion" mixed="true">
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="from" use="optional"  type="xs:string" default="all"/>
		<xs:attribute name="to" use="optional" type="xs:string" default="all"/>
		<xs:attribute name="type" use="optional" default="STATIC">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="STATIC"/>
					<xs:enumeration value="DYNAMIC"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
<!-- 
	attribute:
		name = string
		get = string
		set = string
		all(value?,attributes?,classes?)
 -->
	<xs:complexType name="jmapperAttribute">
		<xs:all>
			<xs:element name="value" type="onlyNameAttribute" minOccurs="0"/>
			<xs:element name="attributes" type="jmapperTargetAttributes" minOccurs="0"/>
			<xs:element name="classes" type="jmapperClasses" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="get" use="optional" type="xs:string" default=""/>
		<xs:attribute name="set" use="optional" type="xs:string" default=""/>
	</xs:complexType>

<!-- 
	global:
		name = string
		get = string
		set = string
		all(attributes?,classes?,excluded?)
 -->
	<xs:complexType name="jmapperGlobal">
		<xs:all>
      <xs:element name="value" type="targetAttribute"/>
			<xs:element name="attributes" type="jmapperTargetAttributes" minOccurs="0"/>
			<xs:element name="classes" type="jmapperClasses" minOccurs="0"/>
			<xs:element name="excluded" type="jmapperExcluded" minOccurs="0"/>
		</xs:all>
	</xs:complexType>
	
<!-- 
	attributes:
		(attribute+)
 -->	
	<xs:complexType name="jmapperTargetAttributes">
		<xs:sequence>
			<xs:element name="attribute" type="targetAttribute" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
<!-- 
	classes:
		(class+)
-->	
	<xs:complexType name="jmapperClasses">
		<xs:sequence>
			<xs:element name="class" type="onlyNameAttribute" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

<!-- 
	excluded:
		(attribute+)
-->	
	<xs:complexType name="jmapperExcluded">
		<xs:sequence>
			<xs:element name="attribute" type="onlyNameAttribute" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
<!--  
    Definition of a target attribute with attributes: "name", "get" and "set"
 -->	
	<xs:complexType name="targetAttribute">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="get" use="optional" type="xs:string" default=""/>
		<xs:attribute name="set" use="optional" type="xs:string" default=""/>
	</xs:complexType>
<!--  
    Definition of an element with only an attribute "name"
 -->	
	<xs:complexType name="onlyNameAttribute">
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== jmapper-framework/jmapper-core/trunk/JMapper Test/src/test/resources/conversions/recursiveTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmapper
xmlns="https://jmapper-framework.googlecode.com"
xmlns:xsi="https://jmapper-framework.googlecode.com/svn"
xsi:noNamespaceSchemaLocation="jmapper.xsd">
  <class name="com.googlecode.jmapper.integrationtest.conversions.bean.DExplicitConversion">
   <attribute name="field">
      <value name="field"/>
    </attribute>
    <conversion name="conversion">
      	return ${source} + " explicit XML converted"; 
    </conversion>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.conversions.bean.SExplicitRecursive">
    <attribute name="sconversion">
      <value name="dconversion"/>
    </attribute>
  </class>
</jmapper>

=== jmapper-framework/jmapper-core/trunk/JMapper Test/src/test/resources/configurations/global.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmapper
xmlns="https://jmapper-framework.googlecode.com"
xmlns:xsi="https://jmapper-framework.googlecode.com/svn"
xsi:noNamespaceSchemaLocation="https://jmapper-framework.googlecode.com/svn/jmapper.xsd">
  <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapD">
    <global>
    	<excluded>
    	   <attribute name ="field3"/>
    	</excluded>
    </global>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapD2">
    <global>
    	<excluded>
    	   <attribute name ="field3"/>
    	</excluded>
    </global>
    <attribute name="field3">
      <value name="field3"/>
    </attribute>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapD6">
    <global>
    	<excluded>
    	   <attribute name ="field2"/>
    	</excluded>
    	<classes>
    	   <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapS2"/>
    	</classes>
    </global>
    <attribute name="field2">
      <value name="field2"/>
      <classes>
    	 <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapS"/>
      </classes>
    </attribute>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapD3">
    <global>
    	<excluded>
    	   <attribute name ="field3"/>
    	</excluded>
    </global>
    <attribute name="field2">
      <value name="notUsed"/>
    </attribute>
  </class>
</jmapper>

=== jmapper-framework/jmapper-core/trunk/JMapper Test/src/test/resources/inheritance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmapper
xmlns="https://jmapper-framework.googlecode.com"
xmlns:xsi="https://jmapper-framework.googlecode.com/svn"
xsi:noNamespaceSchemaLocation="jmapper.xsd">
  <class name="com.googlecode.jmapper.integrationtest.application.bean.ChildConversion">
    <attribute name="specificField1">
      <value name="specificField1"/>
    </attribute>
    <attribute name="specificField2">
      <value name="specificField2"/>
    </attribute>
    <conversion name="conversionChild" from="specificField2">
    	return ${source} + " XML CONVERSION Child";
    </conversion>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.application.bean.ParentConversion">
    <attribute name="commonField1">
      <value name="commonField1"/>
    </attribute>
    <attribute name="commonField2">
      <value name="commonField2"/>
    </attribute>
    <conversion name="conversion" from="commonField1">
    	return ${source} + " XML CONVERSION common";
    </conversion>
    <conversion name="conversion2" from="specificField1">
    	return ${source} + " XML CONVERSION2";
    </conversion>
  </class>
</jmapper>

=== jmapper-framework/jmapper-core/trunk/JMapper Test/src/test/resources/conversions/exceptionTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmapper
xmlns="https://jmapper-framework.googlecode.com"
xmlns:xsi="https://jmapper-framework.googlecode.com/svn"
xsi:noNamespaceSchemaLocation="jmapper.xsd">

   <class name="com.googlecode.jmapper.integrationtest.conversions.bean.ObjSecondD">
    <attribute name="fieldSecondD">
      <value name="fieldSecondS"/>
    </attribute>
    <conversion name="conversion">
      	return new com.googlecode.jmapper.integrationtest.conversions.bean.ObjThirdD(${destination}.getFieldThirdD() + " XML " + ${source}.getFieldThirdS()); 
    </conversion>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.conversions.bean.ObjFirstD">
    <attribute name="fieldFirstD">
      <value name="fieldFirstS"/>
    </attribute>
  </class>
</jmapper>

=== jmapper-framework/jmapper-core/trunk/JMapper Test/src/test/resources/configurations/accessors2.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmapper xmlns="https://jmapper-framework.googlecode.com"
	xmlns:xsi="https://jmapper-framework.googlecode.com/svn"
	xsi:noNamespaceSchemaLocation="https://jmapper-framework.googlecode.com/svn/jmapper.xsd">
	<class
		name="com.googlecode.jmapper.integrationtest.configurations.bean.JMapAccDest2">
		<global>
			<value name="sField2" get="getSSField2" />
			<attributes>
				<attribute name="dField2" get="getDestField2" set="setDestField2"/>
			</attributes>
			
			<!-- provare anche con excluded 
				<excluded>
					<attribute name="dField1" />
				</excluded>
			-->
		</global>
		<attribute name="dField1" get="getDestField1" set="setDestField1">
			<value name="sField1" get="NON_LETTO"/>
		</attribute>
		<attribute name="dField2" get="getDestField2" set="setDestField2">
			<value name="sField2" get="getSSField2"/>
		</attribute>
	</class>
	<class
		name="com.googlecode.jmapper.integrationtest.configurations.bean.JMapAccSrc2">
		<attribute name="sField1" get="getsField1" />
	</class>
</jmapper>

=== jmapper-framework/jmapper-core/trunk/JMapper Test/src/test/resources/configurations/global2.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmapper
xmlns="https://jmapper-framework.googlecode.com"
xmlns:xsi="https://jmapper-framework.googlecode.com/svn"
xsi:noNamespaceSchemaLocation="jmapper.xsd">
  <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapD">
    <global>
    	<value name="field2"/>
    </global>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapD2">
    <global>
    	<value name="field"/>
    	<classes>
    	   <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapS2"/>
    	</classes>
    </global>
    <attribute name="field3">
      <value name="field3"/>
    </attribute>
  </class>
  <class name="com.googlecode.jmapper.integrationtest.configurations.bean.JGlobalMapD3">
    <global>
    	<attributes>
    	   <attribute name ="undefined"/>
    	   <attribute name ="field2"/>
    	   <attribute name ="field3"/>
    	</attributes>
    </global>
    <attribute name="field2">
      <value name="notUsed"/>
    </attribute>
  </class>
</jmapper>

=== jmapper-framework/jmapper-core/trunk/GettingStarted/src/main/resources/xml/staticConversion.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmapper
xmlns="https://jmapper-framework.googlecode.com"
xmlns:xsi="https://jmapper-framework.googlecode.com/svn"
xsi:noNamespaceSchemaLocation="jmapper.xsd">
  <class name="com.googlecode.jmapper.bean.StaticD">
    <attribute name="startDate">
      <value name="startDate"/>
    </attribute>
    <attribute name="endDate">
      <value name="endDate"/>
    </attribute>
  </class>
  <class name="com.googlecode.jmapper.bean.StaticS">
    <conversion name="toDate">
    	return new java.text.SimpleDateFormat("MM/dd/yyyy").parse(${source});
    </conversion>
  </class>
</jmapper>
